# Word embedding using keras embedding layer


In [1]:
import pandas as pd
import numpy as np

from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dense, Flatten

In [2]:
reviews = [
    "nice food",
    "amazing restaurant",
    "too good",
    "just loved it!",
    "will go again",
    "horrible food",
    "never go there",
    "poor service",
    "poor quality",
    "needs improvement",
]

sentiment = np.array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0])

In [3]:
one_hot("amazing restaurant", 30)

[3, 1]

In [19]:
vocab_size = 50
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
print(encoded_reviews)

[[33, 26], [20, 42], [35, 36], [23, 48, 27], [6, 39, 7], [13, 26], [39, 39, 36], [9, 18], [9, 2], [7, 48]]


In [20]:
max_length = 3
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding="post")
print(padded_reviews)

[[33 26  0]
 [20 42  0]
 [35 36  0]
 [23 48 27]
 [ 6 39  7]
 [13 26  0]
 [39 39 36]
 [ 9 18  0]
 [ 9  2  0]
 [ 7 48  0]]


In [21]:
from tensorflow.keras.layers import Input

embedding_vector_size = 5

model = Sequential(
    [
        Input(shape=(max_length,)),
        Embedding(vocab_size, embedding_vector_size, name="embedding"),
        Flatten(),
        Dense(1, activation="sigmoid"),
    ]
)

In [22]:
x = padded_reviews
y = sentiment

In [23]:
model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])

In [24]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 3, 5)           │           250 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_2 (Flatten)             │ (None, 15)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            16 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 266 (1.04 KB)

 Trainable params: 266 (1.04 KB)

 Non-trainable params: 0 (0.00 B)

In [25]:
model.fit(x, y, epochs=50, verbose=0)

In [26]:
# evaluate the model
loss, accuracy = model.evaluate(x, y)
print(f"Loss: {loss:.4f}, Accuracy: {accuracy:.4f}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 181ms/step - accuracy: 1.0000 - loss: 0.6082
Loss: 0.6082, Accuracy: 1.0000


In [27]:
weights = model.get_layer("embedding").get_weights()[0]
len(weights), weights.shape

(50, (50, 5))

In [28]:
weights[11]

array([ 0.00967496, -0.00796967, -0.00989698, -0.02300525,  0.01721913],
      dtype=float32)

In [29]:
weights[3]

array([-0.00513612,  0.01046461,  0.02673913,  0.03188529,  0.03972441],
      dtype=float32)