<a href="https://colab.research.google.com/github/MottuqeBrid/TensorFlow/blob/main/14%20BERT/1%20BERT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# BERT


In [36]:
import tensorflow_hub as hub
import tensorflow as tf
import sys

print("Python:", sys.version)
print("TensorFlow:", tf.__version__)
print("TensorFlow Hub:", hub.__version__)

Python: 3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]
TensorFlow: 2.20.0
TensorFlow Hub: 0.16.1


In [37]:
# https://www.kaggle.com/models/tensorflow/bert/tensorFlow2/bert-en-uncased-l-10-h-768-a-12
preprocessor_url = "https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3"
encoder_url = "https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4"



In [38]:
import tensorflow_text as text
print("TF Text:", text.__version__)


TF Text: 2.20.1


In [39]:
bert_preprocess_model = hub.KerasLayer(preprocessor_url)

In [40]:
text_test = ['nice movie indeed','I love python programming']
text_preprocessed = bert_preprocess_model(text_test)
text_preprocessed.keys()

dict_keys(['input_type_ids', 'input_mask', 'input_word_ids'])

In [41]:
text_preprocessed["input_mask"]

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int32)>

In [42]:
text_preprocessed["input_word_ids"]

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[  101,  3835,  3185,  5262,   102,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0, 

In [44]:
bert_model=hub.KerasLayer(encoder_url)
bert_results = bert_model(text_preprocessed)

In [45]:
bert_results.keys()

dict_keys(['pooled_output', 'sequence_output', 'encoder_outputs', 'default'])

In [46]:
bert_results["pooled_output"]

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.7917738 , -0.21411908,  0.49769568, ...,  0.24465264,
        -0.47334474,  0.8175868 ],
       [-0.917123  , -0.4793518 , -0.7865697 , ..., -0.6175174 ,
        -0.71026856,  0.921843  ]], dtype=float32)>

In [47]:
bert_results["sequence_output"]

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[ 0.07292059,  0.08567812,  0.14476854, ..., -0.09677101,
          0.08722116,  0.07711097],
        [ 0.1783941 , -0.19006115,  0.5034946 , ..., -0.05869832,
          0.32717133, -0.1557856 ],
        [ 0.18701485, -0.43388745, -0.4887515 , ..., -0.15502803,
          0.00145148, -0.24471036],
        ...,
        [ 0.12083067,  0.12884209,  0.46453547, ...,  0.07375515,
          0.17441931,  0.16522099],
        [ 0.07967885, -0.011907  ,  0.5022544 , ...,  0.13777733,
          0.21002221,  0.00624604],
        [-0.07212668, -0.28303468,  0.59033364, ...,  0.4755188 ,
          0.1666848 , -0.08920352]],

       [[-0.07900615,  0.36335114, -0.2110159 , ..., -0.17183767,
          0.16299738,  0.6724269 ],
        [ 0.27883527,  0.43716267, -0.3576473 , ..., -0.04463609,
          0.38315213,  0.5887984 ],
        [ 1.2037672 ,  1.0727022 ,  0.48408717, ...,  0.24920978,
          0.4073093 ,  0.4048182 ],
        ...,

In [49]:
bert_results["encoder_outputs"][-1]

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[ 0.07292059,  0.08567812,  0.14476854, ..., -0.09677101,
          0.08722116,  0.07711097],
        [ 0.1783941 , -0.19006115,  0.5034946 , ..., -0.05869832,
          0.32717133, -0.1557856 ],
        [ 0.18701485, -0.43388745, -0.4887515 , ..., -0.15502803,
          0.00145148, -0.24471036],
        ...,
        [ 0.12083067,  0.12884209,  0.46453547, ...,  0.07375515,
          0.17441931,  0.16522099],
        [ 0.07967885, -0.011907  ,  0.5022544 , ...,  0.13777733,
          0.21002221,  0.00624604],
        [-0.07212668, -0.28303468,  0.59033364, ...,  0.4755188 ,
          0.1666848 , -0.08920352]],

       [[-0.07900615,  0.36335114, -0.2110159 , ..., -0.17183767,
          0.16299738,  0.6724269 ],
        [ 0.27883527,  0.43716267, -0.3576473 , ..., -0.04463609,
          0.38315213,  0.5887984 ],
        [ 1.2037672 ,  1.0727022 ,  0.48408717, ...,  0.24920978,
          0.4073093 ,  0.4048182 ],
        ...,